global:
  resolve_timeout: 5m

route:
  receiver: default-webhook
  group_by: ["alertname", "service", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - matchers:
        - severity="critical"
      receiver: critical-webhook

receivers:
  - name: default-webhook
    webhook_configs:
      - url: http://webhook-catcher:5001/alerts/default
        send_resolved: true

  - name: critical-webhook
    webhook_configs:
      - url: http://webhook-catcher:5001/alerts/critical
        send_resolved: true
