package com.superapp.auth;

public enum SessionEventType {
    SESSION_CREATED,
    SESSION_REVOKED,
    SESSION_PRUNED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_CONFIRMED,
    MFA_CHALLENGE_REQUESTED,
    MFA_VERIFIED,
    TOTP_SETUP_CONFIRMED,
    TOTP_DISABLED,
    TOTP_RECOVERY_REGENERATED
}
